final doctorMapList = [
  {
    "name": "elsafa ",
    "type": "Baby Incubator",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/images/h1.jpg",
    "description": "Infant incubator model BB 200 Luxurious manufactured by Dison instrument and meter One of the best baby incubator in Egypt has special specification and features therefor become advanced infant incubator Baby incubator : Baby incubator BB 200 luxurious has advanced service mount control unit with  2 sensors  air sensor to detect temperature  inside hood and skin temperature to detect baby skin temperature and so providing more and more safety for babies",
  },
  {
    "name": "nile hospital",
    "type": "Baby Incubator",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/images/h2.jpg",
    "description": "Welcome to Nile Hospital – Hurghada “The Castle of Medicine”, your 1st choice to maintain your health.   Nile Hospital is the leader in provision of health care services for the residents and visitors of Hurghada and Red Sea Governorate, Founded in 2005 as a state of art hospital, Equipped with the latest medical technologies and Attracted distinguished senior physicians from the most ranked universities and hospitals allover Egypt, and a very well trained nurses and supporting team. Located in a privileged location between the Ring Road and the Airport Road, close to Hurghada Airport and the Down Town.",
  },
  {
    "name": "elsafa ",
    "type": "Baby Incubator",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image":"assets/images/h3.jpg",
    "description": "Welcome to Nile Hospital – Hurghada “The Castle of Medicine”, your 1st choice to maintain your health.   Nile Hospital is the leader in provision of health care services for the residents and visitors of Hurghada and Red Sea Governorate, Founded in 2005 as a state of art hospital, Equipped with the latest medical technologies and Attracted distinguished senior physicians from the most ranked universities and hospitals allover Egypt, and a very well trained nurses and supporting team. Located in a privileged location between the Ring Road and the Airport Road, close to Hurghada Airport and the Down Town.",
  },
  {
    "name": "nile hospital",
    "type": "Baby Incubator",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image":"assets/images/h4.jpg",
    "description": "Infant incubator model BB 200 Luxurious manufactured by Dison instrument and meter One of the best baby incubator in Egypt has special specification and features therefor become advanced infant incubator Baby incubator : Baby incubator BB 200 luxurious has advanced service mount control unit with  2 sensors  air sensor to detect temperature  inside hood and skin temperature to detect baby skin temperature and so providing more and more safety for babies",
  }
];
